- hosts: vpn_public
  gather_facts: False
  become: yes

  tasks:
    - name: Do an apt-get update & upgrade
      apt:
        upgrade: yes
        update_cache: yes
        force_apt_get: yes

    - name: Nginx setup
      apt: pkg=nginx state=present update_cache=true
      notify:
        - start nginx

    - name: copy index.html
      copy: src=../index.html dest=/var/www/html/index.html mode=0644

    - name: copy cpu and disk monitoring job in server
      copy: src=../../scripts/actual_monitoring.py dest=/usr/bin/monitoring.py mode=755

    - name: Create a cron job for monitoring
      cron: 
        name: disk and cpu monitoring
        minute: "*/5"
        job: "/usr/bin/python3 /usr/bin/monitoring.py >> /var/log/cron_monitoring_error.log  2>&1"

  handlers:
    - name: start nginx
      service: name=nginx state=started
